### ISSUE TITLE
S3 bucket secret and key exposed to EDC consumers as free text

### ISSUE THREAD

**Issue by alpercem70** [eclipse-tractusx/tractusx-edc#1088]
At the moment, the transfer process endpoint of EDC data management API accepts the S3 credentials along with the bucket name and region during a data transfer. EDCs then store these details as is without any encryption.
 
The credentials are then accessible by the end users via the transfer process endpoint. This creates an inherent security risk and access to both read data from and write data to S3 bucket.
 
Suggested Fixes
- Credentials should not be accessible by the management APIs.
- They need to be stored in an encrypted way both on the consumer and provider EDC.
- Processes should exist to prevent different types of data source developers from exposing their credentials without an encrypted format.

**Comment by rafaelmag110** [comment]
Hi Alper,
Specifing the Access and Secret key in the transfer data destination is indeed possible but it should only be done in testing scenarios for the exact reasons you underline in this issue.
The recomended way to assign secret credentials to your data address/destination is to store these keys in the connectors vault with an alias of your choice and assign that alias to a property of said data address/destination.
The name of this property is as of now `secretToken `, however we are probably replacing this in the future because we found an inconsistency with the naming of this property. 
You can follow the development of this case under this issue on upstream: https://github.com/eclipse-edc/Technology-Aws/issues/211

**Comment by florianrusch-zf** [comment]
As @rafaelmag110 provided a good answer I'm going to close this issue.
