### ISSUE TITLE
EDC 0.7.1 → Wrong URLs in Walkthrough and Swagger?

### ISSUE THREAD

**Issue by jerzy-wachowiak** [eclipse-tractusx/tractusx-edc#1315]
### https://github.com/eclipse-tractusx/tractusx-edc/blob/main/docs/usage/management-api-walkthrough/07_edrs.md
Is:
```
POST /v2/edrs HTTP/1.1
Host: https://consumer-control.plane/api/management
X-Api-Key: password
Content-Type: application/json
```
Should be:
```
POST /v2/edrs HTTP/1.1
Host: https://consumer-control.plane/management
X-Api-Key: password
Content-Type: application/json
```
etc.
 
### https://app.swaggerhub.com/apis/eclipse-tractusx-bot/tractusx-edc/0.7.1#/EDR%20Cache/requestEdrEntries

Is
`  /v1/edrs/request:`

Should be:
`  /v2/edrs/request:`
etc

**Comment by wolf4ood** [comment]
Hi @jerzy-wachowiak 

thanks for raising this 

The first issue depends on how you actually configure the management api to be exposed. So the 
`https://consumer-control.plane/api/management` is just an example the relevant part is `/v2/edrs` but i guess is fine to change it also.


The second issue for the EDR api there are two versions, one from upstream EDC which tractusx does not use it (your link)

and the extension of those API for supporting refresh which is available [here](https://app.swaggerhub.com/apis/eclipse-tractusx-bot/tractusx-edc/0.7.1#/Control%20Plane%20EDR%20Api/requestEdrEntries)

The issue is that the swagger doc of tractusx includes also the upstream EDC one and thus it contains both APIs, even if the upstream one is not used/imported.
