### ISSUE TITLE
Rescheduling of dataplane on k8s leads to unregistered dataplane instance

### ISSUE THREAD

**Issue by florianrusch** [eclipse-tractusx/tractusx-edc#1544]
## Describe the bug

We (Cofinity-X) identified a bug within the Dataplane-Selfregistration in terms of restarting the dataplane pods in K8s.

Right now if the Dataplane gets restarted for any reason (e.g. cluster node upgrades or `kubectl rollout restart ...`, k8s will first start the new pod (new dataplane instance is registering itself) and after the new pod is up and running k8s terminates the old pod (old dataplane instance is unregistering itself). This leads to the problem, that the dataplane instance is been marked as "unregistered" (state `400`) in the controlplane dataplane instance list.

### To Reproduce

_Steps to reproduce the behavior:_

1. Deploy the EDC to k8s
2. Trigger a restart of the dataplane (e.g. via `kubectl rollout restart ...`)
3. While having the debug logs enabled you shouldn't be able to see any `[DataPlaneSelectorManagerImpl] DataPlaneInstance my-dataplane is now in state AVAILABLE` statements

### Expected behavior

Dataplane is not in state `unregistered` after a restart

## Context Information

_Add any other context or information about the problem here._

- Used version: Tractus-X EDC 0.7.3, 0.7.4 (and self builded 0.7.5)
- OS: K8s
- Deployment Method: Helm Chart (basically the official one from Tractus-X EDC)

## Workaround

Two workarounds are possible:
1. While using `kubectl delete pod my-dataplane-...` the terminating of the old instance is faster as the creation/startup of the new instance.
2. Setting in the K8s deployment of the Dataplane the `.spec.strategy.type` to `Recreate`. This ensures, that K8s is waiting until the termination of the old pod was done before it creates the new pod. BUT: This leads to a downtime of the dataplane.

## Further notes

I'm not sure what will happen, if we run the dataplane in a high-availability setup...I guess no one really thought about that while implementing the self-registration features. If I'm wrong I would be happy to get pointed to some documentation how this should then be working.

**Comment by rafaelmag110** [comment]
The default behaviour is for the dataplane instance to not unregister itself after termination. It is like this because the unregistration process had issues. We figured keeping the dataplane registration entrace would not lead to any problems (other then an evergrowing list of dataplane is available logs) since you can make all dataplanes register themselves with the same URL, and have an ALB in front. Then, even if the selector picks a DP that in practice is dead, the traffic will reach an existing DP.
On a transfer process the connector never checks if the receiving dataplane has the expected dataplane-id.

If this should be improved and unregistration fixed? Absolutely!

**Comment by wolf4ood** [comment]
Afaik the self unregistered has been fixed in upstream within a configuration and backported [here](https://github.com/eclipse-tractusx/tractusx-edc/pull/1498/files#diff-adbd4eb456731014651db03b42ecba74fd54d5c15fc4a1122fdc3129fff3f4ea)

**Comment by florianrusch** [comment]
Never mind! 😅 You guys are right and it was a problem on our side while doing the debugging...sorry for the confusions!
