### ISSUE TITLE
Chart.yaml and README.md Not Updated to Version 0.7.5 in charts/tractusx-connector

### ISSUE THREAD

**Issue by Sharponentielle** [eclipse-tractusx/tractusx-edc#1586]
## Describe the bug

After the release of version `0.7.5`, the `Chart.yaml` and `README.md` files in the `charts/tractusx-connector` directory still reference version `0.7.3` in the tagged release `0.7.5`. However, the chart version in the `bugfix/0.7.5` branch is correct. This inconsistency can lead to confusion and deployment issues when using the Helm chart from the tagged release.

### To Reproduce

1. Check out the tagged release `0.7.5` from the repository.
2. Navigate to the `charts/tractusx-connector` directory.
3. Open the `Chart.yaml` file.
4. Observe that the `version` and `appVersion` fields are set to `0.7.3` instead of `0.7.5`.
5. Open the `README.md` file in the same directory.
6. Notice that the version badges and installation commands reference version `0.7.3`.

### Expected behavior

The `Chart.yaml` and `README.md` files in the tagged release `0.7.5` should be updated to reflect version `0.7.5`. This ensures consistency across the repository and prevents potential deployment issues with the Helm chart.

### Screenshots/Error Messages

Not applicable.

## Context Information

- Used version: Tagged release `0.7.5`
- OS: N/A
- Docker Version: N/A
- `java --version`: N/A

## Possible Implementation

Update the `version` and `appVersion` fields in `charts/tractusx-connector/Chart.yaml` to `0.7.5` in the tagged release `0.7.5`. Similarly, update all references to version `0.7.3` in `charts/tractusx-connector/README.md` to `0.7.5`, including the version badges and installation instructions.

**Note:** The chart version in the `bugfix/0.7.5` branch is correct; the issue only exists in the tagged release `0.7.5` where the version is incorrect.

**Comment by ndr-brt** [comment]
the problem is indeed in the [`publish-bugfix-release.yaml`](https://github.com/eclipse-tractusx/tractusx-edc/blob/5238961fb787a989fba8db3ce483c7b0c76ab1e1/.github/workflows/publish-bugfix-release.yml#L154):
the `helm-release` job (and all the other jobs) are not starting from the latest commit (the one created by `prepare-bugfix-release`) but from the ref that triggered the workflow.

We need to fix this in 3 parts:
- [ ] manually amend the 0.7.5 chart
- [ ] fix the workflow in the main branch
- [ ] fix the workflow in the bugfix/0.7.6 branch (for the upcoming bugfix release)
