### ISSUE TITLE
How to run locally

### ISSUE THREAD

**Issue by PeterSRWeb3** [eclipse-tractusx/tractusx-edc#1634]
Hello, team,

Sorry for disturbing you, but I'm trying to run the application locally on my machine, but I'm facing some problems. I found the docs folder and I tried to follow the instructions there and run the application, but without success. I faced the following error during running this command:

```
docker run \
    -e EDC_VAULT_SECRETS="key1:secret1;key2:secret2" \
    -p 8080:8080 -p 8181:8181 -p 8282:8282 -p 9090:9090 -p 9999:9999 \
    -v ${CONFIGURATION_PROPERTIES_FILE:-/dev/null}:/app/configuration.properties \
    -v ${LOGGING_PROPERTIES_FILE:-/dev/null}:/app/logging.properties \
    -i edc-runtime-memory:latest
```

And here is the error
```
Caused by: org.eclipse.edc.spi.EdcException: Mandatory config value missing: 'edc.iam.sts.oauth.token.url'. This runtime is not operational.
```

Could you please, point out what else should i run to have this oauth url and setup the application?

Regards,
Petar

**Comment by paullatzelsperger** [comment]
@PeterSRWeb3 first of all, this is not an issue, but - at best - a discussion. I think, not even that.
Second, it most definitely is not a bug, because you are obviously not using the official Tractus-X EDC helm charts. Please, don't raise bugs simply because you are not willing to go the officially supported route.
Third, the exception says in black-and-white what is missing, i.e. a config value. It even tells you which one. 

If you don't read official documentation nor use official distributions of Tx-EDC we can't help you.
