### ISSUE TITLE
Wrong EDR Cache Postgres creds values paths used in Helm Charts

### ISSUE THREAD

**Issue by ayhanmesin-zf** [eclipse-tractusx/tractusx-edc#463]
## Describe the bug

The environment variables used for the EDR Cache Postgres creds in `deployment-dataplane.yaml` are using wrong Helm Chart values. The Helm values cannot be used at this state because of this.

Appearently the structure of the postgres values in `values.yaml` changed (now under `auth`) but the usage of these values in the templates did not get updated.

See [New postgres structure in values.yaml](https://github.com/eclipse-tractusx/tractusx-edc/blob/3db9d24cf5313d4f32a07c76b5744ec2585fed3b/charts/tractusx-connector/values.yaml#LL500C3-L500C3)
See [Usage in templates](https://github.com/eclipse-tractusx/tractusx-edc/blob/3db9d24cf5313d4f32a07c76b5744ec2585fed3b/charts/tractusx-connector/templates/deployment-dataplane.yaml#L157)

### To Reproduce

_Steps to reproduce the behavior:_

1. Install Helm-Chart `Tractusx-Connector`

### Expected behavior

The Helm Chart should get deployed successfully.

### Screenshots/Error Messages

<img width="938" alt="image" src="https://github.com/eclipse-tractusx/tractusx-edc/assets/136314287/f5f377e5-9216-4496-b838-0371b4fc550d">

## Context Informations

_Add any other context about the probleme here._

- Used version: 3db9d24cf5313d4f32a07c76b5744ec2585fed3b
- OS: Mac OS (M1)
- Docker Version: 20.10.23
- `java --version`:

## Possible Implementation

Fix the environment variables in `deployment-dataplane.yaml` by using `postgres.auth.username` & `postgres.auth.password`

**Comment by florianrusch-zf** [comment]
@wolf4ood @paullatzelsperger does someone of you know, why our CI piplines didn't catched this?

**Comment by paullatzelsperger** [comment]
quickly looked into this, and I found the following: the values file we use for testing (`edc-tests/deployment/src/main/resources/helm/tractusx-connector-test.yaml`) contains those (wrong) config entries (`postgresql.username` etc.), therefor Helm does not complain, and the deployment tests are green.

Then, at runtime, the error does not surface because there is a default value configured for `EDC_DATASOURCE_EDR_NAME`, and the username/password never get "used", because our helm tests do not execute any requests against the database.

**Comment by florianrusch-zf** [comment]
Nice! We should then fix the other error as well. @ayhanmesin-zf can you fix it in your PR too?
