### ISSUE TITLE
EDR API: EDR get stuck in REFRESHING state

### ISSUE THREAD

**Issue by dreni** [eclipse-tractusx/tractusx-edc#837]
### WHAT

The EDR renewal doesn't always work when e.g. MIW verification failed. For the specific asset one can't start another EDR request until the 'failed" EDR stuck in REFRESHING state isn't deleted.

In background a retry should happen or a clean up of the failed EDR, if the error of external services (e.g. MIW) still remains.

**Comment by drhansbeck** [comment]
This is in 0.6.0-rc2 - see #855 listed in https://github.com/eclipse-tractusx/tractusx-edc/releases 

Hi @wolf4ood , @dreni , @paullatzelsperger ! 

Thanks for this fix!! Wonderful to see the Tractus-X commnity working together nicely!! 

Possibly: does it make sense to a add 0.6.0-rc2 milestone tag (and hopefully later the 0.6.0 tag)? I very much like the comprehensive listing in https://github.com/eclipse-tractusx/tractusx-edc/releases  . Having release tags on issues would easily allow users who suspect that they are affected to i) check their version against the "fixed in" version ii) allow for their upgrade planning. 
I know this might be too much work, I totally respect that. 

Again:: big thanks for the fix and the good release documentation!!

Best,
Hans

**Comment by paullatzelsperger** [comment]
@drhansbeck I don't know of a way to link issues to releases other than listing them in a release changelog. 
Milestones are not the same thing as releases and they don't always correlate 1:1. Also, we would need a way to link one issue to multiple milestones, because some fixes may be present in multiple releases, just think of backported bugfixes.

I understand the desire to know in which version a desired fix is contained, I think GitHub does not offer that out-of-the box. maybe some third-party tooling exists?
