### ISSUE TITLE
Incomplete OAS documentation for (at least) /edrs

### ISSUE THREAD

**Issue by jluebstorf** [eclipse-tractusx/tractusx-edc#998]
https://app.swaggerhub.com/apis/eclipse-tractusx-bot/tractusx-edc/0.5.3#/Control%20Plane%20EDR%20Api/initiateEdrNegotiation

Request body is missing, schema is incomplete for Policy

**Comment by ndr-brt** [comment]
the issue with the null body is described here: https://github.com/eclipse-edc/GradlePlugins/issues/183 
unfortunately looks like the `openapi-merger` plugin is not that active, but maybe it could be something we could contribute as well. In the [EDC connector client implementation there's a workaround implemented](https://github.com/Think-iT-Labs/edc-connector-client-java/blob/main/build.gradle.kts#L60) that works nicely: just replace all the `example: null` with an empty string

the policy schema is intentionally "empty" because it is 1:1 with the ODRL spec (https://www.w3.org/TR/odrl-model/) and we didn't want to overlap with inconsistent/incomplete documentation.
